# Generated by Django 3.1.1 on 2020-10-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_learn',
            name='cats',
            field=models.CharField(choices=[('flip', 'Flip'), ('grind', 'Grind'), ('slide', 'Slide'), ('manual', 'Manual')], default='flip', max_length=10),
        ),
    ]
