# Generated by Django 3.1.1 on 2020-10-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201014_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_learn',
            name='cats',
            field=models.CharField(choices=[('flip', 'Flip'), ('grind', 'Grind'), ('slide', 'Slide'), ('manual', 'Manual')], max_length=10),
        ),
    ]
